### ISSUE TITLE
Thanks for this action!

### ISSUE THREAD

**Issue by pat-s** [naijabcom/update-formula-homebrew-action#1]
I used it successfully to automate my homebrew releases.

Just wanted to mention though that I needed to look at your repos to succeed in the end as the example is missing some steps. Specifically the part to update the sha.

[Here is](https://github.com/pat-s/rcli/blob/main/.github/workflows/homebrew-release.yml) a full workflow example which is a combination of your [levis](https://github.com/kubeopsskills/levis/tree/develop/.github/workflows) workflows.

**Comment by naijab** [comment]
@pat-s thank you for using this actions. I will add example for repo.
